### ISSUE TITLE
suggest that add onCreate callback so that the user can get "uploadTask" objcet

### ISSUE THREAD

**Issue by iscowei** [tencentyun/cos-wx-sdk-v4#3]
wx.uploadFile does not provide a timeout callback, we have to judge time out for ourself, and interrupt the upload request:
https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-file.html#uploadtask
so we need to get the  "uploadTask" objcet when wx.uploadFile called, used for calling uploadTask.abort();
such as:
```
var uploadTask = wx.uploadFile({
        url: url,
        filePath: tempFilePath,
        name: 'fileContent',
        header: {'Authorization': sign},
        formData: data,
        success: function (result) {
              result.data = JSON.parse(result.data);
              onProgress(null, true);
              success.call(this, result);
	},
        fail: error
});
typeof options.onCreate === 'function' && uploadTask && uploadTask.abort && options.onCreate(uploadTask);

**Comment by carsonxu** [comment]
由于 cos-wx-sdk-v4 限制 20MB 上传，推荐都使用：
https://github.com/tencentyun/cos-wx-sdk-v5
