### ISSUE TITLE
getObject回调数据data不全，没有Body

### ISSUE THREAD

**Issue by baotlake** [tencentyun/cos-wx-sdk-v4#8]
getObject回调data中没有Body,只有headers和statusCode，
我更换lib/cos-wx-sdk-v5.js文件后正常
更换文件来源为：https://github.com/piscium2010/cos-wx-upload-file

**Comment by carsonxu** [comment]
由于 v4 接口只能上传20MB文件，小程序上传 COS 请使用来上传：
https://github.com/tencentyun/cos-wx-sdk-v5

**Comment by carsonxu** [comment]
另外看了一遍，v4 没有这个 getObject 接口，v5 里的 getObject 接口有返回 Body 字符串的

**Comment by BoatLake** [comment]
我说的就是你们的v5版本，getObject回调data没有Body，我更换为其他来源的v5后正常。

**Comment by BoatLake** [comment]
我又重新下载了一边你们这个v5替换后结果依然如此。
